### ISSUE TITLE
Readme does not have a link to the paper in the ACM or IEEE digital library.

### ISSUE THREAD

**Issue by spshetty** [SoftwareEngineeringToolDemos/FSE-2011-Crystal#3]
The link opens up the paper directly instead of the ACM or IEEE page containing the paper.

**Comment by KaranDagar** [comment]
The reason is simple. The original git- links directly to the paper. If you look at original crystal site. I used the same link the originators used. My understanding is that people should have an access to the paper. And a link to it. I think that solves it.

**Comment by KaranDagar** [comment]
This issue was moved to SoftwareEngineeringToolDemos/FSE-2011-Crystal#3
