### ISSUE TITLE
Readme is not consistent with the example readme.

### ISSUE THREAD

**Issue by spshetty** [SoftwareEngineeringToolDemos/FSE-2011-Crystal#5]

**Comment by spshetty** [comment]
Th example-repo shows that the readme should have some links to the original project in the format shown below
Here are some links to the original project:
* The Official Project Page, including source code
* The Tool on the Visual Studio Gallery
* A Video of the Tool

The readme for Crystal does not contain any of these

**Comment by gshah** [comment]
Looks like I am added in this repo by mistake. Kindly remove me.

Thanks.

On Wednesday, October 21, 2015, spshetty <notifications@github.com> wrote:

> Th example-repo shows that the readme should have some links to the
> original project in the format shown below
> Here are some links to the original project:
>
>    - The Official Project Page, including source code
>    - The Tool on the Visual Studio Gallery
>    - A Video of the Tool
>
> The readme for Crystal does not contain any of these
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoftwareEngineeringToolDemos/FSE-2011-Crystal/issues/5#issuecomment-149771531>
> .
>


-- 
Gaurav Shah
---------------------------------------------
The weak can never forgive. Forgiveness is the attribute of the strong.
''Mahatma Gandhi''

**Comment by KaranDagar** [comment]
Hi spshetty,

If you dont mind my saying you said it yourself "example-repo". Example is just an example it is not a set guideline.

Thanks,
Karan

**Comment by spshetty** [comment]
Hey,

You are not going to be graded based on our feedback. So us raising issues
wont affect your marks. We have been told to raise issues if we are not
sure and do any changes for improvement. So we might be wrong in raising
 some of the issues, but you can close them later !

**Comment by KaranDagar** [comment]
This issue was moved to SoftwareEngineeringToolDemos/FSE-2011-Crystal#5
